### PR TITLE
Styled and implemented routes.

### PR DESCRIPTION
**Pull request by eserpin**
Created a display for when a user has no logs.
Implemented new api routes. 
Also styled the dashboard further

### CODE REVIEW

**Review by cmcrow2 — APPROVED** [review]

**Comment by cmcrow2** [comment]
Accidentally approved it looks like this is failing some checks

**Review by kennyctran — CHANGES_REQUESTED** [review]
Blocking this merge until fixed

**Review by kennyctran — COMMENTED** [review]
Please change localhost to env variable

**Review by kennyctran — APPROVED** [review]
looks good!

**Pull request merged**
